### ISSUE TITLE
Error in OrangeHRM 4.8

### ISSUE THREAD

**Issue by lindiii** [Manu58/OrangeExport#1]
![image](https://user-images.githubusercontent.com/20233739/126649652-e28235ab-833e-4847-b1c5-75b9624b085d.png)
I'm attaching the error which i receive when i modify the files and try to print or create an pdf

**Comment by Manu58** [comment]
This patch is for an older version.

**Comment by lindiii** [comment]
Now it is also working on this version, maybe it was a cache problem

**Comment by mostafa-zaied** [comment]
@Manu58 @lindiii How to test after copying the files?
As I want to generate a csv file from Timesheet
